- name: "Start Ursulas"
  hosts: "{{ 'tag_Role_' + lookup('env', 'NUCYPHER_NETWORK_NAME') }}"
  user: ubuntu
  gather_facts: false

  tasks:
    - name: Delete config directory.
      file:
        state: absent
        path: ".local/share/nucypher/"
